# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce737faf90959a884739fa7378f70eb585ee6fb330f45850de61ca70c66614a54b226652935c3cd36a7fa106ab7284d22fa00a38100408012711c45d53a6b0b3

test:
  secret_key_base: 227249a441cef85bece9d6bc10b61e36fa8a239037b9867bfa51bc7bde6b476b3b910605cb111f8f8d116184ce93771f8ae42be512b7fbe8fec62b0a4e272c76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
